name: Latest blog posts

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@nipunaranasinghe"
          max_post_count: 4
          date_format: "mmm yyyy"
          template: "- [$title]($url) — $date$newline"
