# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (once a day)
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC

  # Lines below let you run workflow manually and on each commit
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: NipunaRanasinghe
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          # plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          # plugin_languages_limit: 8
          # plugin_languages_recent_categories: markup, programming
          # plugin_languages_recent_days: 14
          # plugin_languages_recent_load: 300
          # plugin_languages_sections: most-used
          # plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
